### ISSUE TITLE
Custom list counter

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-issues#115]
```css
.li1,
.li2,
.body ol,
.body ul {
  counter-reset: li;
}
.li1 > li::before,
.li2 > li::before,
.body ol > li::before,
.body ul > li::before {
  font-family: Cambria, Georgia, serif;
  font-weight: bold;
  color: #cca700;
  margin-top: 0.71428571428571rem;
  margin-bottom: 0.17857142857143rem;
  display: block;
  content: counter(li,lower-roman);
  counter-increment: li;
}
.li1 > li:first-child::before,
.li2 > li:first-child::before,
.body ol > li:first-child::before,
.body ul > li:first-child::before {
  margin-top: 0;
}

.li2 > li::before,
.body ul > li::before {
  content: counter(li,square);
  margin-bottom: 0.11904761904762rem;
}
```
