### ISSUE TITLE
Printing even more exact

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-issues#133]
```css
* {
-webkit-print-color-adjust: exact;
printer-colors: exact;
color-adjust: exact;}
```

https://stackoverflow.com/a/45944620/922323

Still looks like IE won't work.
