### ISSUE TITLE
Overflow and scroll

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-issues#139]
Useful for mobile web apps:

```css
html,
body { overflow-x: hidden; }
html { overflow-y: scroll; }
```
