### ISSUE TITLE
Box sizing

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-issues#14]
Alternative technique:

``` css
html                 { box-sizing: border-box; }
*, *:before, *:after { box-sizing: inherit; }
```

As seen here:

http://vincentp.me/blog/use-cases-for-calc/

http://codepen.io/vipickering/pen/gaMZWY
