### ISSUE TITLE
Horizontal rules

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-issues#159]
```css
hr,
.hr {
	border: 0;
	border-top: 1px solid #999;
	height: 0;
	margin: 15px 0 20px;
	padding: 0;
	-webkit-box-sizing: content-box;
	   -moz-box-sizing: content-box;
	    -ms-box-sizing: content-box;
	     -o-box-sizing: content-box;
	        box-sizing: content-box;
}
```
