### ISSUE TITLE
Multiple-border box

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-issues#177]
```css
.ap_box-title {
    color: #fff;
    font-weight: 700;
    font-size: 1.8rem;
    letter-spacing: 0.05em;
    background: #008e42;
    border: 0.2rem solid #fff;
    border-radius: 0.2rem;
    box-shadow:
        0 0 0 0.5rem #008e42/*,
        0 0 0 1rem #fff,
        0 0 0 1.5rem #008e42*/;
    margin: 0;
    padding: 1rem;
    position: absolute;
    left: -3.6rem;
    top: -2rem;
}
```

![screenshot 2018-05-08 14 47 07](https://user-images.githubusercontent.com/218624/39784830-b581762e-52ce-11e8-8133-6f6ae5fc5f2d.png)
