### ISSUE TITLE
Two column layout with flexbox enhancement

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-issues#181]
```css
.layout {
    background: #888;
    height: 100%;
}
.layout::after {
    clear: both;
    content: "";
    display: table;
}

.layout-primary {
    margin-left: 30%;
}
.layout-primary > :first-child {
    margin-top: 0 !important;
}
.layout-primary > :last-child {
    margin-bottom: 0 !important;
}

.layout-secondary {
    background: #fff;
    float: left;
    width: 30%;
}

/* Flexbox enhancements (Edge + modern browsers): */
@supports (display: flex) {

    .layout {
        display: flex;
        height: 100%;
    }
    .layout-primary {
        flex: 1;
        margin-left: 0;
        min-width: 0;
    }
    .layout-secondary {
        flex: 0 0 30%;
        min-width: 18rem;
        max-width: 25rem;
    }

}
```

```html
<!doctype html>
<html lang=en>
<head>
<meta charset=utf-8>
<title></title>
<link rel="stylesheet" href="assets/styles/test.css">
</head>
<body>
<div class="layout">
    <aside class="layout-secondary" role="complementary">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    </aside>
    <main class="layout-primary" role="main">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    </main>
</div>
</body>
</html>
```

Global styles needed to make this work:

```css
html {
    height: 100%;
}
body {
    min-height: 100%;
    height: 100vh;
}

body {
    margin: 0;
}
```
