### ISSUE TITLE
Flexbox full page body and html

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-issues#183]
```html
<body class="container">
  <header>…</header>
  <main class="content">…</main>
  <footer>…</footer>
</body>
```

```css
.container {
  display: flex;
  min-height: 100vh;
  flex-direction: column;
}
.content {
  flex: 1;
}
```

I tend to not put flexbox on the body as I usually have non-flexbox immediate children elements. In this case, you could experiment with:

```css
body {
     height: 100vh;
}
```

… and apply `.container` to a child div of the `body` element.

**WARNING:** [iOS may have issues with `100vh`](https://stackoverflow.com/a/37113430/922323); __test thoroughly__.
