### ISSUE TITLE
Disable pointer events (mouse click)

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-issues#186]
```css
.avoid-clicks {
    pointer-events: none;
    -webkit-touch-callout: none;
}
```
