### ISSUE TITLE
CSS debug utility

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-issues#187]
Here’s a few pretty simple techniques:

## Give it borders

```css
.thing {
    border: 1px solid red;
}
```

Now you can see what `thing` is doing … Keep in mind, border can affect [box model](https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS/Box_model).

## Outline everything

```css
# Click anywhere to outlines (change `*` to a specific element for more control):
body:active * {
    box-shadow: inset 0 0 0 5px rgba(255, 0, 0, 0.5);
}
```

The `box-shadow` can also be applied to a specific rule set.

# Use `x` to turn off properties

Disable property by making it invalid:

```css
.foo {
    color: red;
    border: 1px solid blue;
    xdisplay: block;
}
```
