### ISSUE TITLE
Hide/show with .no-js/.js classes

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-issues#195]
```css
.js .ap_util-hide-if-js {
    display: none;
}
.no-js .ap_util-show-if-js {
    display: none;
}
```

```html
<!doctype html>
<html class="no-js" lang="en" dir="ltr">
<head>

    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8">

    <script>/*! no-js uglified | https://gist.github.com/mhulse/4704893 */!function(e){e.documentElement.className=e.documentElement.className.replace(/\bno-js\b/,"js")}(document);</script>

```
