### ISSUE TITLE
Tables spacing

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-issues#199]
```css
table {
    border-collapse: separate;
    border-spacing: 3px;
}
```

![](https://user-images.githubusercontent.com/218624/49475851-31c2b380-f7cd-11e8-9bc4-33d143748abd.png)
