### ISSUE TITLE
Stupid hamburger menu

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-issues#207]
# TO BE CLEANED UP!

Using Font Awesome 4:

```css
#nav {
	background: #fff;
	margin-bottom: 20px;
	border: .1rem solid #355a66;
	margin-top: -.1rem;
	display: none;
}
#nav ul {
	margin: 0;
	padding: 0;
	list-style: none;

}
#nav ul::after {
	content: "";
	display: table;
	clear: both;
}
#nav li {
	color: #355a66;
	letter-spacing: .05em;
	font-size: 1.8rem;
	line-height: 1;
	width: 100%;
	float: left;
	display: inline;
}
#nav li:first-child { float: right;}
#nav a {
	display: block;
	padding: 1rem 1rem 1.1rem;
	position: relative;
	border-bottom: .1rem solid #355a66;
	margin-bottom: -.1rem;
}
#nav a,
#nav a:visited {
	color: #1bb0ce;
	text-decoration: none;
}
#nav a:visited:hover,
#nav a:focus,
#nav a:focus:hover,
#nav a:hover,
#nav a:active {
	color: #355a66;
	text-decoration: none;
	background: #d1eff5;
}
#nav a.selected,
#nav a.selected:visited:hover,
#nav a.selected:focus,
#nav a.selected:focus:hover,
#nav a.selected:hover,
#nav a.selected:active {
	color: #fff;
	text-decoration: none;
	background: #355a66;
	box-shadow: none !important;
}
@media (min-width: 48rem) {
    #nav {
		border: 0;
		border-top: .5rem solid #355a66;
		box-shadow: 0 -.5rem 0 #cadae0 inset;
		margin-top: -.5rem;
		display: block !important;
	}
	#nav li { width: auto; }
	#nav a {
		padding-bottom: 1.5rem;
		box-shadow: none;
		border: 0;
	}
	#nav a:visited:hover,
	#nav a:focus,
	#nav a:focus:hover,
	#nav a:hover,
	#nav a:active { box-shadow: 0 -.5rem 0 #1bb0ce inset; }
}

.toggle {
	color: #000;
	font-size: 2rem;
	background: transparent;
	width: 5rem;
	height: 5rem;
	display: block;
	cursor: pointer;
	cursor: hand;
	position: absolute;
	right: 1rem;
	top: 50%;
	-webkit-transform: translateY(-50%);
	   -moz-transform: translateY(-50%);
	    -ms-transform: translateY(-50%);
	     -o-transform: translateY(-50%);
	        transform: translateY(-50%);
}
.toggle::after {
	content: "\f0c9";
	font-family: FontAwesome;
	font-style: normal;
	font-weight: normal;
	font-size: 3rem;
	line-height: 1;
	position: absolute;
	top: 50%;
	left: 50%;
	-webkit-transform: translate(-50%, -50%);
	   -moz-transform: translate(-50%, -50%);
	    -ms-transform: translate(-50%, -50%);
	     -o-transform: translate(-50%, -50%);
	        transform: translate(-50%, -50%);
}
.toggle.opened::after { content: "\f00d"; }
@media (min-width: 48rem) {
	.toggle { display: none; }
}
```

```js
window.addEventListener('DOMContentLoaded', function() {

	(function (window, document) {

		var menu = document.getElementById('nav');
		var toggle = document.getElementById('toggle');

		menu.classList.add('closed');
		toggle.classList.add('closed');

		function toggleMenu() {

			$(toggle).toggleClass('opened closed');

			$(menu).slideToggle('fast', function() {
				$(menu).toggleClass('opened closed');
			});

		}

		function closeMenu() {

			if (menu.classList.contains('opened')) {

				toggleMenu();

			}

		}

		document.getElementById('toggle').addEventListener('click', function (e) {

			toggleMenu();

		});

	})(this, this.document);

});
```

Put this on your page:

```html
<div id="toggle" class="toggle closed">
    <s class="bar"></s><s class="bar"></s>
</div>
```

And this somewhere else:

```html
<nav id="nav" class="closed faux" role="navigation">
    <ul>
        <li>
            <a href="/">
                Login
            </a>
        </li>
        <li>
            <a href="/">
                Home
            </a>
        </li>
    </ul>
</nav>
```
