### ISSUE TITLE
Split update

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-issues#57]
``` css
/*
<div class="split">
    <div>left</div>
    <div>middle</div>
    <div>right</div>
</div>
*/

.split > div {
    text-align: center;
    margin: 10px 0;
}
.split > div > * { display: inline-block; }

@media (min-width: 480px) {
    .split::after {
        content: "";
        display: table;
        clear: both;
    }
    .split {
        position: relative;
        margin: 10px 0;
    }
    .split > div {
        width: 100%;
        margin: 0;
        position: absolute;
        z-index: 1;
    }
    .split > div:first-child,
    .split > div:last-child {
        width: auto;
        position: relative;
        z-index: 2;
    }
    .split > div:first-child {
        text-align: left;
        float: left;
    }
    .split > div:last-child {
        text-align: right;
        float: right;
    }
}
```

Addon style:

``` css
.foot {
    margin-top: 20px;
    padding-top: 10px;
    border-top: 1px solid #138d9c;
}
```

HTML:

``` html
<footer class="split">
    <div>
        <p>
            <a href="#">Forgot password?</a>
            <br>
            <a href="#">Register</a>
        </p>
    </div>
    <div>
        <button class="button" type="button" name="button-1" onclick="return false;">Login</button>
    </div>
</footer>
```
