### ISSUE TITLE
Unselectable

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-issues#85]
``` css
[unselectable] {
    -webkit-touch-callout: none;
      -webkit-user-select: none;
       -khtml-user-select: none;
         -khtml-user-drag: none;
         -moz-user-select: none;
          -ms-user-select: none;
              user-select: none;
    -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
    -webkit-tap-highlight-color: transparent;
    outline-style: none;
}
[unselectable]::webkit-selection { background-color: transparent; }
[unselectable]::-moz-selection { background-color: transparent; }
[unselectable]::selection { background-color: transparent; }
```
